name: bustan_kopi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.0-134.1.beta <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  velocity_x: 3.4.0
  hive: 2.1.0
  hive_flutter: 1.1.0
  intl: 0.17.0
  image_picker: ^0.8.5
  path_provider: ^2.0.9
  group_radio_button: ^1.2.0
  pinput: ^2.2.7
  
  flutter: 
    sdk: flutter
  

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  build_runner: 2.1.10
  hive_generator: 1.1.2
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

